### PR TITLE
Bug 1471210 - remove functionality now implemented in ci-admin

### PR DESCRIPTION
**Pull request by djmitche**
This leaves a bunch of scripts that aren't the greatest (e.g., for workerType modification).  I'd be happy to see those deleted or modified too.  But this at least removes functionality that is now superseded by ci-admin.

### CODE REVIEW

**Comment by djmitche** [comment]
@petemoore ping?

**Review by petemoore — APPROVED** [review]
Looks great, thanks for deleting!

**Comment by djmitche** [comment]
Tanks!

**Review by tomprince — COMMENTED** [review]
I think that 
- `make-scm-group-roles`
- `update-action-hook-perms`
- `util/projects.js`
- `util/action-hooks.js`
are all things that have been moved to ci-admin as well.

**Pull request merged**
